# docker-compose.yml

version: "3"
services:
  web:
    build: .
    container_name: app
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    entrypoint: flask run --host "0.0.0.0" --port "5000"